version: '3'
services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carsdb
    ports:
      - "5432:5432"

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: nestjs-container
    ports:
      - "3333:3333"  
    env_file:
      - .env
    depends_on:
      - db  